{% set name = "symbolic" %}
{% set version = "12.15.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/symbolic-{{ version }}.tar.gz
    sha256: 0c4ee306165939b2769f88cd29d6e64f62fe2046f47aaddf570041b4f2bac6c0
  - url: https://raw.githubusercontent.com/getsentry/symbolic/refs/tags/{{ version }}/LICENSE
    sha256: 989aeccdc0127d426c2509116eff70f21b4552f08ebe9f468acc539cd121a692

build:
  # Windows build skipped due to OOM, re-enable on the feedstock
  skip: true  # [win]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - unzip rustsrc.zip
    - cd rustsrc
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - unzip     # [unix]
    - m2-unzip  # [win]
  host:
    - python
    - setuptools
    - milksnake >=0.1.2
    - pip
  run:
    - python
    - milksnake >=0.1.2

test:
  imports:
    - symbolic
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A python library for dealing with symbol files and more.
  home: https://github.com/getsentry/symbolic
  dev_url: https://github.com/getsentry/symbolic
  license: MIT
  license_file: 
   - LICENSE
   - rustsrc/THIRDPARTY.yml

extra:
  recipe-maintainers:
    - xhochy
